### ISSUE TITLE
Unchecky for Chrome

### ISSUE THREAD

**Issue by JohnKiller** [Unchecky/unchecky-bho#1]
OK here it is a simple implementation of this script in chrome:

**manifest.json**

```
{
    "name": "Unchecky for Chrome",
    "version": "0.0.1",
    "manifest_version": 2,
    "description": "Unchecky for Chrome",
    "content_scripts": [
        {
            "matches": ["*://get.adobe.com/*"],
            "js": ["unchecky.js"]
        }
    ]
}
```

**unchecky.js**

```
var rules = [
    {
        id: 'offerCheckbox',
        urls: [
            'get.adobe.com/flashplayer',
            'get.adobe.com/reader'
        ]
    }
];

for(i = 0; i < rules.length; i++){
    var id = rules[i].id;
    var urls = rules[i].urls;
    for(j = 0; j < urls.length; j++){
        if(location.href.indexOf(urls[j]) != -1){
            setInterval(function(){
                var ck = document.getElementById(id);
                if(ck.checked){
                    ck.click();
                }
            }, 1000);
            break;
        }
    }
}
```

I can create a project on github but i don't want to steal the name, so i prefer to share it here first :)

Like you, i'm not very experienced in browser extensions, but it's a start...

**Comment by m417z** [comment]
That's great!

In order for it to be ready for production, there has to be a way to actually check the offer if the user really wants to.
Ideally, there should be a warning, as Unchecky does for the desktop apps, but for start just allowing it to be checked is good enough.
I think that stopping the timer after running `ck.click();` will do (the script resets after a refresh, right?).

Another important thing is: how do I integrate it with the installer? How do I uninstall it? What if Chrome is running when Unchecky is uninstalled? Are you familiar with all this?

> I can create a project on github but i don't want to steal the name, so i prefer to share it here first :)

I can create a repository for you to fork. Then you could work on the fork, and I'll pull the code when it's ready. What do you think?

**Comment by JohnKiller** [comment]
I can attach an event handler on the checkbox to display that alert. For the installation, i found this after a quick search in google:
http://stackoverflow.com/questions/8535429/installing-chrome-extension-from-nsis-installer

I need to investigate more, but it's definetly possible (or we can just publish it on Google Market and then launch the browser).

For the repository, can you create it and add me as a contributor to do things faster?

**Comment by m417z** [comment]
Yeah, I found this too. Shouldn't be a problem.
Going through the market doesn't sound like a good idea, as I'll have to wait for their staff to approve it, etc.

> For the repository, can you create it and add me as a contributor to do things faster?

Done.

**Comment by JohnKiller** [comment]
uncEHcky-for-chrome, lol

**Comment by m417z** [comment]
Oops, fixed :)

**Comment by JohnKiller** [comment]
First commit done!

**Comment by m417z** [comment]
:thumbsup:
